---
name: Build and Push Docker Image to Docker Hub

on:
  release:
    types: [ "published" ]

env:
  IMAGE_NAME: ${{ github.repository }} # github.repository as <account>/<repo>

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --tag ${{ env.IMAGE_NAME }}:latest --file Dockerfile . --no-cache

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test the Docker image
        run: docker run --rm --name sag ${{ env.IMAGE_NAME }}:latest

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set tag output for release
        id: rel
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest, ${{ env.IMAGE_NAME }}:${{ steps.rel.outputs.tag }}
